version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      METEOR_SETTINGS: '{"binance":{"baseUrl":"https://testnet.binance.vision","apiKey":"YOUR_BINANCE_API_KEY","secretKey":"YOUR_BINANCE_SECRET_KEY","endpoints":{"getAccountData":"/api/v3/account"}}}'
      PORT: 3000

  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    ports:
      - 27017:27017

volumes:
  data: